# -*- coding: utf-8 -*-
"""deploApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MME6BU1OCGhvCBA2QqOTv572rfK9_uN0
"""

import streamlit as st
import pickle
import pandas as pd
import os

# Get the current directory
BASE_DIR = os.getcwd()

# Load the necessary pickle files
try:
    df_new = pickle.load(open(os.path.join(BASE_DIR, 'df_new.pkl'), 'rb'))
    df = pickle.load(open(os.path.join(BASE_DIR, 'df.pkl'), 'rb'))
    similarity_scores = pickle.load(open(os.path.join(BASE_DIR, 'similarity_scores.pkl'), 'rb'))
except FileNotFoundError as e:
    st.error(f"❌ Error: {e}. Please check if the required files are uploaded.")
    st.stop()

# Streamlit UI
st.title("📚 Book Recommendation System")

# User Input
selected_book = st.selectbox("Choose a book", df['Title'].values)

# Function to Recommend Books
def recommend_books(book_name, df, similarity_scores):
    if book_name not in df['Title'].values:
        return ["Book not found. Please try another one."]
    
    book_index = df[df['Title'] == book_name].index[0]
    distances = similarity_scores[book_index]
    recommended_indices = sorted(list(enumerate(distances)), key=lambda x: x[1], reverse=True)[1:6]
    
    recommended_books = [df.iloc[i[0]]['Title'] for i in recommended_indices]
    return recommended_books

# Get Recommendations
if st.button("Recommend"):
    recommendations = recommend_books(selected_book, df, similarity_scores)
    st.subheader("📖 Recommended Books:")
    for book in recommendations:
        st.write(f"📌 {book}")



st.header("Top 10 books by maximum checkouts")
st.dataframe(df4_new1)

